use serde::{Deserialize, Serialize};

/// A structured plan for transforming a workload profile.
/// Generated by AI, editable by human, executed by deterministic engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransformPlan {
    pub version: u8,
    pub source: PlanSource,
    pub analysis: PlanAnalysis,
    pub groups: Vec<QueryGroup>,
    pub transforms: Vec<TransformRule>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanSource {
    pub profile: String,
    pub prompt: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanAnalysis {
    pub total_queries: u64,
    pub total_sessions: u64,
    pub groups_identified: usize,
}

/// A group of queries identified by shared table access patterns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryGroup {
    pub name: String,
    pub description: String,
    pub tables: Vec<String>,
    pub query_indices: Vec<usize>,
    pub session_ids: Vec<u64>,
    pub query_count: usize,
}

/// A transform rule to apply to the workload.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum TransformRule {
    Scale {
        group: String,
        factor: f64,
        #[serde(default = "default_stagger")]
        stagger_ms: u64,
    },
    Inject {
        description: String,
        sql: String,
        after_group: String,
        #[serde(default = "default_frequency")]
        frequency: f64,
        #[serde(default = "default_duration")]
        estimated_duration_us: u64,
    },
    InjectSession {
        description: String,
        queries: Vec<InjectedQuery>,
        repeat: u32,
        #[serde(default = "default_interval")]
        interval_ms: u64,
    },
    Remove {
        group: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InjectedQuery {
    pub sql: String,
    pub duration_us: u64,
}

fn default_stagger() -> u64 {
    10
}
fn default_frequency() -> f64 {
    1.0
}
fn default_duration() -> u64 {
    1000
}
fn default_interval() -> u64 {
    1000
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transform_plan_toml_roundtrip() {
        let plan = TransformPlan {
            version: 1,
            source: PlanSource {
                profile: "test.wkl".into(),
                prompt: "Scale product queries 5x".into(),
            },
            analysis: PlanAnalysis {
                total_queries: 100,
                total_sessions: 5,
                groups_identified: 2,
            },
            groups: vec![QueryGroup {
                name: "product_catalog".into(),
                description: "Product browsing queries".into(),
                tables: vec!["products".into(), "categories".into()],
                query_indices: vec![0, 1, 5, 10],
                session_ids: vec![1, 3],
                query_count: 40,
            }],
            transforms: vec![
                TransformRule::Scale {
                    group: "product_catalog".into(),
                    factor: 5.0,
                    stagger_ms: 10,
                },
                TransformRule::Inject {
                    description: "Review lookup".into(),
                    sql: "SELECT * FROM reviews WHERE product_id = $1".into(),
                    after_group: "product_catalog".into(),
                    frequency: 0.8,
                    estimated_duration_us: 5000,
                },
                TransformRule::InjectSession {
                    description: "Background job".into(),
                    queries: vec![InjectedQuery {
                        sql: "INSERT INTO reviews VALUES ($1)".into(),
                        duration_us: 2000,
                    }],
                    repeat: 10,
                    interval_ms: 1000,
                },
                TransformRule::Remove {
                    group: "reporting".into(),
                },
            ],
        };

        let toml_str = toml::to_string_pretty(&plan).unwrap();
        let parsed: TransformPlan = toml::from_str(&toml_str).unwrap();
        assert_eq!(parsed.version, 1);
        assert_eq!(parsed.groups.len(), 1);
        assert_eq!(parsed.transforms.len(), 4);
        assert_eq!(parsed.groups[0].name, "product_catalog");
    }

    #[test]
    fn test_transform_plan_json_roundtrip() {
        let plan = TransformPlan {
            version: 1,
            source: PlanSource {
                profile: "test.wkl".into(),
                prompt: "test".into(),
            },
            analysis: PlanAnalysis {
                total_queries: 10,
                total_sessions: 2,
                groups_identified: 1,
            },
            groups: vec![QueryGroup {
                name: "products".into(),
                description: "".into(),
                tables: vec!["products".into()],
                query_indices: vec![0],
                session_ids: vec![1],
                query_count: 1,
            }],
            transforms: vec![TransformRule::Scale {
                group: "products".into(),
                factor: 3.0,
                stagger_ms: 10,
            }],
        };

        let json_str = serde_json::to_string(&plan).unwrap();
        let parsed: TransformPlan = serde_json::from_str(&json_str).unwrap();
        assert_eq!(parsed.groups.len(), 1);
        assert_eq!(parsed.transforms.len(), 1);
    }
}
