#!/bin/bash
# Restore db-b from pg_basebackup + WAL replay to a named restore point.
#
# This script runs INSIDE the db-b-pitr container. It:
# 1. Copies the base backup to the PG data directory
# 2. Configures recovery to replay WAL from the archive to the restore point
# 3. Starts PostgreSQL in recovery mode
#
# The restore point name is passed as $RESTORE_POINT (set by docker-compose).
#
# Usage:
#   RESTORE_POINT=pg_retest_capture_20260325_112712 \
#   docker compose -f docker-compose.benchmark.yml up db-b-pitr

set -e

PGDATA="/var/lib/postgresql/data"
BACKUP_DIR="/backups/base"
WAL_ARCHIVE="/var/lib/postgresql/wal_archive"
RESTORE_POINT="${RESTORE_POINT:-}"

echo "=== pg-retest PITR: Restoring to point-in-time ==="
echo "  Backup:        $BACKUP_DIR"
echo "  WAL archive:   $WAL_ARCHIVE"
echo "  Restore point: ${RESTORE_POINT:-<latest>}"

# Verify base backup exists
if [ ! -d "$BACKUP_DIR" ] || [ ! -f "$BACKUP_DIR/PG_VERSION" ]; then
    echo "ERROR: No base backup found at $BACKUP_DIR"
    echo "Run: docker compose -f docker-compose.benchmark.yml exec db-a bash -c 'pg_basebackup -D /backups/base -U demo -Fp -Xs -P -R --checkpoint=fast'"
    exit 1
fi

# Clear existing data directory
echo "  Clearing data directory..."
rm -rf "$PGDATA"/*

# Copy base backup to data directory
echo "  Copying base backup..."
cp -a "$BACKUP_DIR"/. "$PGDATA"/

# Remove standby.signal if present (we want PITR recovery, not streaming replication)
rm -f "$PGDATA/standby.signal"

# Create recovery signal file (this triggers PITR, not standby mode)
touch "$PGDATA/recovery.signal"

# Write recovery configuration — override any streaming replication config from pg_basebackup
cat > "$PGDATA/postgresql.auto.conf" <<EOF
# PITR recovery configuration (generated by pitr-restore.sh)
# Use WAL archive for replay, not streaming replication
restore_command = 'cp $WAL_ARCHIVE/%f %p 2>/dev/null || false'
recovery_target_action = 'promote'
EOF

# Set restore target
if [ -n "$RESTORE_POINT" ]; then
    echo "recovery_target_name = '$RESTORE_POINT'" >> "$PGDATA/postgresql.auto.conf"
    echo "  Target: restore point '$RESTORE_POINT'"
else
    echo "  Target: latest available WAL"
fi

# Fix permissions
chown -R postgres:postgres "$PGDATA"
chmod 700 "$PGDATA"

# Start PostgreSQL — it will enter recovery mode, replay WAL, then promote
echo "  Starting PostgreSQL in recovery mode..."
exec postgres \
    -D "$PGDATA" \
    -c "wal_level=replica" \
    -c "archive_mode=off" \
    -c "log_min_messages=warning"
